<a href="https://colab.research.google.com/github/sidhu2690/Torch/blob/main/00_torch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
print(f"Torch version: {torch.__version__}")

Torch version: 2.6.0+cu124


In [7]:
print(f"Cuda Available: {torch.cuda.is_available()}")

Cuda Available: True


In [10]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cuda


# Scalars

In [14]:
scalar = torch.tensor(100)
print(scalar, scalar.shape)

tensor(100) torch.Size([])


# Vectors

In [16]:
vector = torch.tensor([10])
print(vector, vector.shape)

tensor([10]) torch.Size([1])


# Matrices

In [18]:
matrices = torch.tensor([[10, 12],
                         [12, 12]])
print(matrices, matrices.shape)

tensor([[10, 12],
        [12, 12]]) torch.Size([2, 2])


# 3D tensors

In [24]:
tensor = torch.tensor([[[10, 10],
                        [10, 10]],
                       [[10, 10],
                        [10, 10]]])
print(tensor, tensor.shape)

tensor([[[10, 10],
         [10, 10]],

        [[10, 10],
         [10, 10]]]) torch.Size([2, 2, 2])


# Datatypes

In [27]:
t = torch.tensor(10, dtype = torch.float32)
t.dtype

torch.float32

# Tensor Operations

In [28]:
a = torch.tensor([1, 2, 3, 4, 5])
b = torch.tensor([5, 6, 7, 8, 0])

In [36]:
a.shape, b.shape

(torch.Size([5]), torch.Size([5]))

In [30]:
print(a+b)

tensor([ 6,  8, 10, 12,  5])


In [31]:
print(a*b)

tensor([ 5, 12, 21, 32,  0])


In [32]:
print(a/b)

tensor([0.2000, 0.3333, 0.4286, 0.5000,    inf])


In [33]:
print(a**2)

tensor([ 1,  4,  9, 16, 25])


## Matrix multiplication

In [34]:
torch.matmul(a, b)

tensor(70)

In [37]:
torch.matmul(a,b) == a@b

tensor(True)

## Broadcasting

In [43]:
a = torch.randn(1,2)
b = torch.randn(2,3)
print(f" {torch.matmul(a,b)}, Shape: {torch.matmul(a,b).shape}")

 tensor([[ 3.8940, -1.9102,  0.7607]]), Shape: torch.Size([1, 3])


## Reshaping and manipulation of tensors

In [50]:
x = torch.arange(1, 10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
x.shape

torch.Size([9])

In [48]:
x.reshape(3, 3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [51]:
x.view(3, 3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [63]:
x.unsqueeze(0), x.unsqueeze(0).shape  # Add dimension

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [64]:
x.unsqueeze(1), x.unsqueeze(1).shape  # Add dimension

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [65]:
x.squeeze() # Remove dimension

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Other operations

In [67]:
a = torch.tensor([1, 2])
b = torch.tensor([3, 4])

In [73]:
torch.cat([a,b])  # concatenate along 0 dim

tensor([1, 2, 3, 4])

In [74]:
torch.hstack([a,b]) # horizontal stacking

tensor([1, 2, 3, 4])

In [75]:
torch.vstack([a,b]) # vertical stacking

tensor([[1, 2],
        [3, 4]])

# NumPy and PyTorch Interoperability

In [76]:
import numpy as np

In [79]:
array = np.array([1, 2, 3, 4, 5])
tensor = torch.from_numpy(array)
tensor

tensor([1, 2, 3, 4, 5])

In [80]:
tensor.numpy()

array([1, 2, 3, 4, 5])

# Automatic differentiation

In [84]:
x = torch.tensor(2, dtype= torch.float32, requires_grad = True)

y = 2 * x ** 2 + 3

# dy/dx = 2 * 2* x = 4x = 4*2= 8

y.backward()
x.grad

tensor(8.)

### Stop gradient you can use:

In [87]:
y = x * 2
y

tensor(4., grad_fn=<MulBackward0>)

In [88]:
with torch.inference_mode():
  y = x * 2
  print(y)

tensor(4.)


In [89]:
with torch.no_grad():
  y = x * 2
  print(y)

tensor(4.)


In [91]:
y = x.detach() * 2
y

tensor(4.)

# Moving to device

In [95]:
x.to(device)
x.device

device(type='cpu')

# Setting Seed

In [96]:
torch.manual_seed(42)

In [97]:
# For cude
if torch.cuda.is_available():
  torch.cuda.manual_seed(42)

# Other functions

In [98]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([1, 2, 4])

print(torch.eq(a, b))         # element-wise
print(torch.equal(a, b))      # exact match (True/False)


tensor([ True,  True, False])
False


In [100]:
x = torch.tensor([[1, 2], [3, 4]], dtype = torch.float32)

print(x.sum())
print(x.mean())
print(x.max(), x.argmax())
print(x.min(), x.argmin())

# Along dimensions
print(x.sum(dim=0))  # sum across rows
print(x.sum(dim=1))  # sum across columns


tensor(10.)
tensor(2.5000)
tensor(4.) tensor(3)
tensor(1.) tensor(0)
tensor([4., 6.])
tensor([3., 7.])


### Tensor Type Conversion

In [101]:
x = torch.tensor([1, 2, 3])
print(x.dtype)

torch.int64


In [103]:
# Float conversion
x_f = x.float()
x_f

tensor([1., 2., 3.])

In [104]:
# Long (int64)
x_long = x.long()
x_long

tensor([1, 2, 3])